// @ts-nocheck
import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'article',
  title: '资讯文章',
  type: 'document',
  fields: [
    // 基础信息 - 6语言支持
    defineField({
      name: 'title',
      title: '文章标题 (多语言)',
      type: 'object',
      fields: [
        { name: 'zh', title: '中文 (必填)', type: 'string', validation: (Rule: any) => Rule.required() },
        { name: 'en', title: 'English (必填)', type: 'string', validation: (Rule: any) => Rule.required() },
        { name: 'id', title: 'Bahasa Indonesia', type: 'string' },
        { name: 'th', title: 'ภาษาไทย', type: 'string' },
        { name: 'vi', title: 'Tiếng Việt', type: 'string' },
        { name: 'ar', title: 'العربية', type: 'string' },
      ],
    }),
    defineField({
      name: 'slug',
      title: 'URL标识',
      type: 'slug',
      options: {
        source: 'title.zh',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    }),
    
    // 分类
    defineField({
      name: 'category',
      title: '文章分类',
      type: 'reference',
      to: [{ type: 'articleCategory' }],
      validation: (Rule: any) => Rule.required(),
    }),
    
    // 标签
    defineField({
      name: 'tags',
      title: '标签',
      type: 'array',
      of: [{ type: 'string' }],
      description: '用于SEO的关键词标签，如：LED技术、智能传感、UV消毒等',
    }),
    
    // 摘要 - 6语言支持
    defineField({
      name: 'excerpt',
      title: '文章摘要 (多语言)',
      type: 'object',
      description: '用于列表展示和Meta描述',
      fields: [
        { name: 'zh', title: '中文', type: 'text', rows: 2 },
        { name: 'en', title: 'English', type: 'text', rows: 2 },
        { name: 'id', title: 'Bahasa Indonesia', type: 'text', rows: 2 },
        { name: 'th', title: 'ภาษาไทย', type: 'text', rows: 2 },
        { name: 'vi', title: 'Tiếng Việt', type: 'text', rows: 2 },
        { name: 'ar', title: 'العربية', type: 'text', rows: 2 },
      ],
    }),
    
    // 正文内容 - 6语言支持
    defineField({
      name: 'content',
      title: '文章内容 (多语言)',
      type: 'object',
      fields: [
        { 
          name: 'zh', 
          title: '中文', 
          type: 'array', 
          of: [
            { type: 'block' },
            { type: 'image', options: { hotspot: true } }
          ] 
        },
        { 
          name: 'en', 
          title: 'English', 
          type: 'array', 
          of: [
            { type: 'block' },
            { type: 'image', options: { hotspot: true } }
          ] 
        },
        { 
          name: 'id', 
          title: 'Bahasa Indonesia', 
          type: 'array', 
          of: [
            { type: 'block' },
            { type: 'image', options: { hotspot: true } }
          ] 
        },
        { 
          name: 'th', 
          title: 'ภาษาไทย', 
          type: 'array', 
          of: [
            { type: 'block' },
            { type: 'image', options: { hotspot: true } }
          ] 
        },
        { 
          name: 'vi', 
          title: 'Tiếng Việt', 
          type: 'array', 
          of: [
            { type: 'block' },
            { type: 'image', options: { hotspot: true } }
          ] 
        },
        { 
          name: 'ar', 
          title: 'العربية', 
          type: 'array', 
          of: [
            { type: 'block' },
            { type: 'image', options: { hotspot: true } }
          ] 
        },
      ],
    }),
    
    // 封面图
    defineField({
      name: 'coverImage',
      title: '封面图',
      type: 'image',
      options: {
        hotspot: true,
      },
      description: '用于列表展示和Open Graph分享',
    }),
    
    // 作者信息
    defineField({
      name: 'author',
      title: '作者',
      type: 'object',
      fields: [
        { name: 'name', title: '作者名称', type: 'string', initialValue: 'GOPRO LED' },
        { name: 'avatar', title: '头像', type: 'image' },
      ],
    }),
    
    // 发布设置
    defineField({
      name: 'publishedAt',
      title: '发布时间',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'status',
      title: '发布状态',
      type: 'string',
      options: {
        list: [
          { title: '已发布', value: 'published' },
          { title: '草稿', value: 'draft' },
          { title: '定时发布', value: 'scheduled' },
        ],
      },
      initialValue: 'published',
    }),
    
    // 来源信息（用于自动化）
    defineField({
      name: 'source',
      title: '文章来源',
      type: 'object',
      description: '自动化抓取时使用',
      fields: [
        { name: 'url', title: '原文链接', type: 'url' },
        { name: 'name', title: '来源网站', type: 'string' },
        { name: 'isAutoGenerated', title: '是否AI生成', type: 'boolean', initialValue: false },
      ],
    }),
    
    // SEO 设置
    defineField({
      name: 'seo',
      title: 'SEO 设置',
      type: 'object',
      fields: [
        {
          name: 'metaTitle',
          title: 'Meta 标题 (多语言)',
          type: 'object',
          fields: [
            { name: 'zh', title: '中文', type: 'string' },
            { name: 'en', title: 'English', type: 'string' },
            { name: 'id', title: 'Bahasa Indonesia', type: 'string' },
            { name: 'th', title: 'ภาษาไทย', type: 'string' },
            { name: 'vi', title: 'Tiếng Việt', type: 'string' },
            { name: 'ar', title: 'العربية', type: 'string' },
          ],
        },
        {
          name: 'metaDescription',
          title: 'Meta 描述 (多语言)',
          type: 'object',
          fields: [
            { name: 'zh', title: '中文', type: 'text', rows: 2 },
            { name: 'en', title: 'English', type: 'text', rows: 2 },
            { name: 'id', title: 'Bahasa Indonesia', type: 'text', rows: 2 },
            { name: 'th', title: 'ภาษาไทย', type: 'text', rows: 2 },
            { name: 'vi', title: 'Tiếng Việt', type: 'text', rows: 2 },
            { name: 'ar', title: 'العربية', type: 'text', rows: 2 },
          ],
        },
        {
          name: 'keywords',
          title: 'SEO关键词',
          type: 'array',
          of: [{ type: 'string' }],
          description: '页面关键词，用于搜索引擎优化',
        },
      ],
    }),
    
    // 阅读统计
    defineField({
      name: 'viewCount',
      title: '阅读次数',
      type: 'number',
      initialValue: 0,
      readOnly: true,
    }),
    
    // 特色文章
    defineField({
      name: 'isFeatured',
      title: '设为推荐文章',
      type: 'boolean',
      initialValue: false,
      description: '推荐文章会在首页展示',
    }),
  ],
  
  preview: {
    select: {
      title: 'title.zh',
      subtitle: 'category.title.zh',
      media: 'coverImage',
    },
  },
  
  orderings: [
    {
      title: '发布时间, 最新',
      name: 'publishedAtDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
  ],
});
